### Post useBalance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1234567890",
  "amount": 2000
}

### Post useBalance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1234567890",
  "amount": 2000
}

### Post cancelBalance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "accountNumber": "1234567890",
  "transactionId": "fa71987eb8a34e76848f189feff034fb",
  "amount": 1000
}

### Get queryTransaction
GET http://localhost:8080/transaction/cffa8957573943b7b065d79a177ffdd0


